// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: grpc/app_balancer.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AppBalancerClient is the client API for AppBalancer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppBalancerClient interface {
	// A simple RPC.
	//
	// Obtains the feature at a given position.
	//
	// A feature with an empty name is returned if there's no feature at the given
	// position.
	UpdateSpeed(ctx context.Context, in *UpdatePodSpeed, opts ...grpc.CallOption) (*Result, error)
	CreateApp(ctx context.Context, in *CreatePodApp, opts ...grpc.CallOption) (*Result, error)
}

type appBalancerClient struct {
	cc grpc.ClientConnInterface
}

func NewAppBalancerClient(cc grpc.ClientConnInterface) AppBalancerClient {
	return &appBalancerClient{cc}
}

func (c *appBalancerClient) UpdateSpeed(ctx context.Context, in *UpdatePodSpeed, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/appbalancer.AppBalancer/UpdateSpeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appBalancerClient) CreateApp(ctx context.Context, in *CreatePodApp, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/appbalancer.AppBalancer/CreateApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppBalancerServer is the server API for AppBalancer service.
// All implementations must embed UnimplementedAppBalancerServer
// for forward compatibility
type AppBalancerServer interface {
	// A simple RPC.
	//
	// Obtains the feature at a given position.
	//
	// A feature with an empty name is returned if there's no feature at the given
	// position.
	UpdateSpeed(context.Context, *UpdatePodSpeed) (*Result, error)
	CreateApp(context.Context, *CreatePodApp) (*Result, error)
	mustEmbedUnimplementedAppBalancerServer()
}

// UnimplementedAppBalancerServer must be embedded to have forward compatible implementations.
type UnimplementedAppBalancerServer struct {
}

func (UnimplementedAppBalancerServer) UpdateSpeed(context.Context, *UpdatePodSpeed) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSpeed not implemented")
}
func (UnimplementedAppBalancerServer) CreateApp(context.Context, *CreatePodApp) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateApp not implemented")
}
func (UnimplementedAppBalancerServer) mustEmbedUnimplementedAppBalancerServer() {}

// UnsafeAppBalancerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppBalancerServer will
// result in compilation errors.
type UnsafeAppBalancerServer interface {
	mustEmbedUnimplementedAppBalancerServer()
}

func RegisterAppBalancerServer(s grpc.ServiceRegistrar, srv AppBalancerServer) {
	s.RegisterService(&AppBalancer_ServiceDesc, srv)
}

func _AppBalancer_UpdateSpeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePodSpeed)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppBalancerServer).UpdateSpeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appbalancer.AppBalancer/UpdateSpeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppBalancerServer).UpdateSpeed(ctx, req.(*UpdatePodSpeed))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppBalancer_CreateApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePodApp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppBalancerServer).CreateApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appbalancer.AppBalancer/CreateApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppBalancerServer).CreateApp(ctx, req.(*CreatePodApp))
	}
	return interceptor(ctx, in, info, handler)
}

// AppBalancer_ServiceDesc is the grpc.ServiceDesc for AppBalancer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppBalancer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "appbalancer.AppBalancer",
	HandlerType: (*AppBalancerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateSpeed",
			Handler:    _AppBalancer_UpdateSpeed_Handler,
		},
		{
			MethodName: "CreateApp",
			Handler:    _AppBalancer_CreateApp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/app_balancer.proto",
}
